config/routes.rb
Rails.application.routes.draw do

  post 'session/signin'
  delete 'session/signout'

  ActiveAdmin.routes(self)
  root 'welcome#index'

  post 'teams/subscribe'

  resources :leagues, only: [:index, :show] do
   resources :games, except: [:show];
   resources :teams do
     resources :events
      member do
        post 'will_attend'
        delete 'not_attend'
      end
   end
  end
  resources :users, except: [:destroy]

end

app/models/league.rb
# == Schema Information
#
# Table name: leagues
#
#  id          :integer          not null, primary key
#  skill       :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class League < ActiveRecord::Base
  #associations
  has_many :teams
  has_many :games

  #validators
  validates :skill, presence: true, uniqueness: { case_sensitive: false }

  #scopes
  scope :league_weekly_games, lambda { where("time between ? and ?", 1.day.ago, 6.days.from_now).order('time asc')}

  #methods
  def league_avg_goals
    league_total_goals = self.teams.collect {|teams| teams.total_goals}.reduce :+
    league_avg = league_total_goals / self.teams.count.to_f
    return league_avg.round(2)
  end

  def league_avg_wins
    league_total_wins = self.teams.collect {|teams| teams.winner_games}.reduce :+
    league_avg = league_total_wins / self.teams.count.to_f
    return league_avg.round(2)
  end

  def league_avg_losses
    league_total_losses = self.teams.collect {|teams| teams.loser_games}.reduce :+
    league_avg = league_total_losses / self.teams.count.to_f
    return league_avg.round(2)
  end

  def league_avg_points
    league_total_points = self.teams.collect {|teams| teams.game_points}.reduce :+
    league_avg = league_total_points / self.teams.count.to_f
    return league_avg.round(2)
  end

  def league_avg_penalties
    league_total_penalties = self.teams.collect {|teams| teams.team_penalties}.reduce :+
    league_avg = league_total_penalties / self.teams.count.to_f
    return league_avg.round(2)
  end

  def league_avg_ga
    league_total_ga = self.teams.collect {|teams| teams.goals_against}.reduce :+
    league_avg = league_total_ga / self.teams.count.to_f
    return league_avg.round(2)
  end

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  before_action :set_league, only: [:show]

  def index
    @leagues = League.all
  end

  def show
  end

  private

  def set_league
    @league = League.find(params[:id])
    @league_weekly_games = @league.games.weekly_games
    @league_prior_games = @league.games.prior_games
    @league_current_games = @league.games.current_games
  end

end

app/helpers/league_helper.rb
module LeagueHelper
end

app/views/leagues/_current_schedule.html.erb
<div class="statictablewrapper">
  <div class="table-responsive" style="max-width:800px;">
    <table class="table">
    <h3>
      Weekly Games: <%= 1.day.ago.strftime("%a %b, %e") %> - <%= 6.days.from_now.strftime("%a %b, %e") %>
    </h3>
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Home Team</th>
          <th>Away Team</th>
        </tr>
      </thead>
      <tbody>
        <% @league_weekly_games.each do |game| %>
        <tr style="background:white;">
          <td><%= game.time.strftime("%a %b, %e") %></td>
          <td><%= game.time.strftime("%R") %></td>
          <td><%= game.home_team.name %></td>
          <td><%= game.away_team.try(:name) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/leagues/_historic_schedule.html.erb
<div class="searchtablewrapper">
  <div class="display responsive no-wrap">
    <table id="lscorestable" class="table-condensed">
    <h3>
      Game Scores
    </h3>
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Home Team</th>
          <th>Goals</th>
          <th>Away Team</th>
          <th>Goals</th>
          <th>Game Winner</th>
        </tr>
      </thead>
      <tbody>
        <% @league_prior_games.each do |game| %>
        <tr style="background:white;">
          <td><%= game.time.strftime("%a %b, %e") %></td>
          <td><%= game.time.strftime("%R") %></td>
          <td><%= game.home_team.try(:name) %></td>
          <td><%= game.home_goals %></td>
          <td><%= game.away_team.try(:name) %></td>
          <td><%= game.away_goals %></td>
          <td><%= game.winner.try(:name) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/leagues/_league_standings.html.erb
<div class="searchtablewrapper">
  <div class="display responsive no-wrap">
    <table id="lstatstable" class="table-condensed">
    <h3>League Stats:</h3>
    <thead>
      <tr>
        <th>Team</th>
        <th>GP</th>
        <th>Wins</th>
        <th>Losses</th>
        <th>Points</th>
        <th>Goals</th>
        <th>GA</th>
        <th>PIM</th>
      </tr>
    </thead>
    <tbody>
      <% @league.teams.active.each do |team| %>
        <tr>
          <td><%= link_to team.name, league_team_path(team.league, team) %></td>
          <td><%= team.total_games_played %></td>
          <td><%= team.winner_games %></td>
          <td><%= team.loser_games %></td>
          <td><%= team.game_points %></td>
          <td><%= team.total_goals %></td>
          <td><%= team.goals_against %></td>
          <td><%= team.team_penalties %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/leagues/_schedule.html.erb
<div class="searchtablewrapper">
  <div class="display responsive no-wrap">
    <table id="lstable" class="table-condensed">
      <h3>Season Schedule</h3>
        <thead>
          <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Home Team</th>
            <th>Away Team</th>
          </tr>
        </thead>
        <tbody>
          <% @league_current_games.each do |game| %>
          <tr>
            <td><%= game.time.strftime("%a %b, %e") %></td>
            <td><%= game.time.strftime("%R") %></td>
            <td><%= game.home_team.name %></td>
            <td><%= game.away_team.try(:name) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/leagues/_teams.html.erb
<div class="searchtablewrapper">
  <div class="display responsive no-wrap">
    <table id="lstatstable" class="table-condensed">
    <h3>League Stats:</h3>
    <thead>
      <tr>
        <th>Team</th>
        <th>GP</th>
        <th>Wins</th>
        <th>Losses</th>
        <th>Points</th>
        <th>Goals</th>
        <th>GA</th>
        <th>PIM</th>
      </tr>
    </thead>
    <tbody>
      <% @league.teams.active.each do |team| %>
        <tr>
          <td><%= link_to team.name, league_team_path(team.league, team) %></td>
          <td><%= team.total_games_played %></td>
          <td><%= team.winner_games %></td>
          <td><%= team.loser_games %></td>
          <td><%= team.game_points %></td>
          <td><%= team.total_goals %></td>
          <td><%= team.goals_against %></td>
          <td><%= team.team_penalties %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/leagues/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="page-header">
      <h1><%= @league.skill %> League Page
        <small> //
          <span class="dropdown">
            <a class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown">All Teams</a>
            <span class="caret"></span>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              <% @league.teams.each do |team| %>
                <li role="presentation"><%= link_to team.name, league_team_path(@league, team) %></li>
              <% end %>
            </ul>
          </span>
        <br>
          <% if signed_in? %>
            <%= link_to 'New Team Registration', new_league_team_path(@league) %>
          <% end %>
        </small>
      </h1>
      <div class="button-group">
        <label>
          <input type="radio" name="button-group" value="item" id="leagueWeeklyScheduleButton" checked>
          <span class="button-group-item">Weekly Schedule</span>
        </label>
        <label>
          <input type="radio" name="button-group" value="other-item" id="leagueSeasonButton">
          <span class="button-group-item">Season Schedual</span>
        </label>
        <label>
          <input type="radio" name="button-group" value="other-item" id="leagueScoresButton">
          <span class="button-group-item">Scores</span>
        </label>
        <label>
          <input type="radio" name="button-group" value="third" id="leagueStatsButton">
          <span class="button-group-item">League Stats</span>
        </label>
        <% if signed_in? && current_user.admin? %>
          <span class="dropdown" style="float:right;">
            <button type="button" class="btn btn-primary dropdown-toggle" type="button" id="dropdownAdminMenu" data-toggle="dropdown" aria-expanded="true">
              Admin Actions
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              <li role="presentation"><%= link_to 'Add a Game', new_league_game_path(@league) %></li>
              <li role="presentation"><%= link_to 'View/Edit Games', league_games_path(@league) %></li>
            </ul>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row" id="leagueWeeklySchedule">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'current_schedule' %>
  </div>
</div>

<div class="row" style="display:none" id="leagueStats">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'league_standings' %>
  </div>
</div>

<div class="row" style="display:none" id="leagueScores">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'historic_schedule' %>
  </div>
</div>

<div class="row" style="display:none" id="leagueSeason">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'schedule' %>
  </div>
</div>