config/routes.rb
Rails.application.routes.draw do

  post 'session/signin'
  delete 'session/signout'

  ActiveAdmin.routes(self)
  root 'welcome#index'

  post 'teams/subscribe'

  resources :leagues, only: [:index, :show] do
   resources :games, except: [:show];
   resources :teams do
     resources :events
      member do
        post 'will_attend'
        delete 'not_attend'
      end
   end
  end
  resources :users, except: [:destroy]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  avatar          :string
#  phone           :string
#  bio             :text
#  active          :boolean          default("true")
#  admin           :boolean          default("false")
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  deleted_at      :datetime
#

class User < ActiveRecord::Base
  has_secure_password

  #associations
  has_many :teams, through: :rosters
  has_many :rosters, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :game_attendances, dependent: :destroy

  #validations
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, on: :create

  mount_uploader :avatar, AvatarUploader

  # Methods
  def team_owner?(team)
    self.email == team.owner
  end

  def team_member?(team)
    team.users.find_by(id: self)
  end

  def profile?(user, current_user)
    user == current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def edit
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        UserMailer.welcome_email(@user).deliver_later
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        flash[:error] = "We were unable to sign you up. #{@user.errors.full_messages.join('. ')}"
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    def set_user
      @user = User.where(id: current_user).find_by(id: params[:id])
      redirect_to root_path, alert: "Permission not configured." if @user.nil?
    end

    def user_params
      params.require(:user).permit(:goals, :penalties, :games_played, :assists, :role, :phone, :bio, :password, :name, :email, :avatar, :avatar_cache, :remove_avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="searchtablewrapper">
<%= bootstrap_form_for(@user) do |f| %>
  <%= f.alert_message 'Please fix the following errors:' %>
  <%= f.text_field :name %>
  <%= f.email_field :email %>
  <%= f.password_field :password %>
  <%= f.file_field :avatar %>
  <%= f.hidden_field :avatar_cache %>
  <%= image_tag(@user.avatar.url(:thumb)) if @user.avatar? %>
  <%= f.check_box :remove_avatar, label: 'Remove avatar' %>
  <%= f.text_field :phone %>
  <%= f.text_area :bio %>
  <%= f.submit "Submit" %>
<% end %>
</div>

app/views/users/_player_team_stats.html.erb
<% @user.rosters.each do |roster| %>
  <h3><%= link_to roster.team.name, league_team_path(roster.team.league, roster.team) %><small> <%= roster.team.league.skill %> League</small></h3>
  <p><strong><%= roster.games_played %> Games Played</strong></p>

          <div class="statictablewrapper">
            <div class="table-responsive" style="max-width:800px;">
              <table class="table">
              <h3>
                Schedule: <%= 1.day.ago.strftime("%a %b, %e") %> - <%= 6.days.from_now.strftime("%a %b, %e") %>
              </h3>
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Home Team</th>
                    <th>Away Team</th>
                  <% if signed_in? && current_user.team_member?(roster.team) && current_user.profile?(@user, current_user)%>
                    <th>Players Going</th>
                    <th>Players Not RSVP'd</th>
                    <th>RSVP'd</th>
                    <th>Attending?</th>
                  <% end %>
                  </tr>
                </thead>
                <tbody>
                  <% roster.team.games.weekly_games.each do |game| %>
                  <tr style="background:white;">
                    <td><%= game.time.strftime("%a %b, %e") %></td>
                    <td><%= game.time.strftime("%R") %></td>
                    <td><%= game.home_team.name %></td>
                    <td><%= game.away_team.try(:name) %></td>
                    <% if signed_in? && current_user.team_member?(roster.team) && current_user.profile?(@user, current_user)%>
                      <td><%= game.team_attendance(roster.team).count %></td>
                      <td><%= game.not_attending(roster.team) %></td>
                      <td>
                      <% if game.attending?(current_user, roster.team) %>
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                      <% end %>
                      </td>
                      <td>
                      <% if game.attending?(current_user, roster.team) %>
                        <%= form_tag(not_attend_league_team_path(game.league, roster.team), method: 'delete') do %>
                          <%= hidden_field_tag(:game_id, game.id) %>
                          <%= submit_tag "Attending", {class: "btn btn-primary btn-xs"} %>
                        <% end %>
                      <% else %>
                        <%= form_tag will_attend_league_team_path(game.league, roster.team) do %>
                          <%= hidden_field_tag(:game_id, game.id) %>
                          <%= submit_tag "NOT Attending", {class: "btn btn-danger btn-xs"} %>
                        <% end %>
                      <% end %>
                      </td>
                    <% end %>
                  <% end %>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

  <p><h4>Goals</h4></p>

    <div class="statsbox">
      <b>Individual Goals</b><br><br>
      <b>Avg Team Goals</b>
    </div>
    <section>

      <div class="progress">
        <% if roster.goals < 1 %>
          <div>0</div>
        <% else %>
        <div class="progress-bar" role="progressbar" aria-valuemin="0" style="width:<%= roster.goals %>%;min-width: 2em;max-width: 600px;"><%= roster.goals %></div>
        <% end %>
      </div>

      <div class="progress">
        <% if roster.team.total_goals < 1 %>
          <div>0</div>
        <% else %>
          <div class="progress-bar" role="progressbar" aria-valuemin="0" style="width:<%= roster.team.team_avg_goals %>%;max-width: 600px;min-width:2em;"><%= roster.team.team_avg_goals %></div>
        <% end %>
      </div>

    </section>

  <p><h4>Assists</h4></p>

    <div class="statsbox">
      <b>Individual Assists</b><br><br>
      <b>Avg Team Assists</b>
    </div>
    <section>
      <div class="progress">
        <% if roster.assists < 1 %>
          <div>0</div>
        <% else %>
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuemin="0" style="width:<%= roster.assists %>%;min-width: 2em;max-width: 600px;"><%= roster.assists %></div>
        <% end %>
      </div>
      <div class="progress">
        <% if roster.team.total_goals < 1 %>
          <div>0</div>
        <% else %>
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuemin="0" style="width:<%= roster.team.team_avg_assists %>%;max-width: 600px;min-width:2em;"><%= roster.team.team_avg_assists %></div>
        <% end %>
      </div>
    </section>

  <p><h4>Penalty Minutes</h4></p>
    <div class="statsbox">
      <b>PIMS</b><br><br>
      <b>Avg Team PIMS</b>
    </div>
    <section>
      <div class="progress">
        <% if roster.penalties < 1 %>
          <div>0</div>
        <% else %>
          <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuemin="0" style="width:<%= roster.penalties %>%;min-width: 2em;max-width: 600px;"><%= roster.penalties %></div>
        <% end %>
      </div>
      <div class="progress">
        <% if roster.team.team_penalties < 1 %>
          <div>0</div>
        <% else %>
          <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuemin="0" style="width:<%= roster.team.team_avg_penalties %>%;max-width: 600px;min-width:2em;"><%= roster.team.team_avg_penalties %></div>
        <% end %>
      </div>
    </section>
    <br>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit User Profile</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
<% @users.each do |user| %>
  <li><%= image_tag(user.avatar.url(:thumb)) %> <%= link_to user.name, user_path(user) %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3"><h1>New User</h1></div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">

  <div class="col-md-3 col-md-offset-1">
    <h1><%= @user.name %></h1>
    <%= image_tag(@user.avatar.url, style:"width:180px; border:2px solid #a1a1a1;") %>
    <br>
    <% if @user.profile?(@user, current_user) %>
      <%= link_to 'Edit Profile', edit_user_path(@user) %>
    <% end %>

    <br>
    Contact Information:
    <li>Email: <%= @user.email %></li>
    <li>Phone: <%= @user.phone %></li>
    About:
    <li><%= @user.bio %></li>
  </div>

  <div class="col-md-6">
    <h3>Player Stats</h3>
  </div>

  <div class="col-md-7">
    <%= render 'player_team_stats' %>
  </div>

</div>

<div class="row">
  <div class="col-md-4">
    <br><br><br><br>
  </div>
</div>