config/routes.rb
Rails.application.routes.draw do

  post 'session/signin'
  delete 'session/signout'

  ActiveAdmin.routes(self)
  root 'welcome#index'

  post 'teams/subscribe'

  resources :leagues, only: [:index, :show] do
   resources :games, except: [:show];
   resources :teams do
     resources :events
      member do
        post 'will_attend'
        delete 'not_attend'
      end
   end
  end
  resources :users, except: [:destroy]

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @leagues = League.all
    @rosters = Roster.all
    @roster_sample = @rosters.sample(3)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="jumbo">
      <h1>Ice Sports Forum</h1>
      <p>Ice Sports Forum's Adult Hockey program is open for all those 18-70+ years old. We have been rated #1 in the Southeast and in the top 10 nationwide by USA Hockey for the last 4 years. Our Adult program currently consists of 98 teams spread out among 13 leagues. This lets us cater to those who have never skated before, all the way to those with Stanley Cup rings.</p>
      <% if !signed_in? %>
        <br><p><%= link_to 'Sign Up!', new_user_path, class: "btn btn-danger btn-lg" %></p>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <h2>Featured Players</h2>
  </div>
</div>

<br>

<div class="row" style="padding: 0px 15px 0px 15px;">
  <div class="col-md-10 col-md-offset-1" style="padding-left:40px;">
      <% @roster_sample.each do |roster| %>
        <div class="col-md-4">
          <div class="clearfix">
            <%= link_to image_tag(roster.user.avatar.thumb.url, id: "featurePlayers"), roster.user %>
            <p class="fpText" style="padding-top:10px;">
              <%= link_to roster.user.name, roster.user %>
            </p>
            <p class="fpText">
              G: <%= roster.total_goals(roster.user) %> |
              A: <%= roster.total_assists(roster.user) %> |
              PIMS: <%= roster.total_pims(roster.user) %>
            </p>
            <p class="fpText">
              Teams: <%= roster.user.teams.collect {|t|t.name}.join(' | ') %>
            </p>
          </div>
        </div>
      <% end %>
  </div>
</div>

<br><br><br><br><br>

<div class="row" style="padding: 0px 15px 0px 15px;">
  <div class="col-md-10 col-md-offset-1 leaguelisting">
    <h3>Leagues Directory:</h3>

    <% @leagues.each do |league| %>
      <div class="col-md-3">
        <li style="display:inline;"><h4><%= link_to league.skill.upcase, league_path(league) %></h4></li>
          <ul>
          <% league.teams.each do |team| %>
            <li><strong><%= link_to team.name.titlecase, [league, team] %></strong></li>
          <% end %>
          </ul>
      </div>
    <% end %>

  </div>
</div>