config/routes.rb
Rails.application.routes.draw do

  post 'session/signin'
  delete 'session/signout'

  ActiveAdmin.routes(self)
  root 'welcome#index'

  post 'teams/subscribe'

  resources :leagues, only: [:index, :show] do
   resources :games, except: [:show];
   resources :teams do
     resources :events
      member do
        post 'will_attend'
        delete 'not_attend'
      end
   end
  end
  resources :users, except: [:destroy]

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
      <span style="float:left;"><%= link_to image_tag('ice_forum.png'), root_path %></span>

        <% if signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Sign Out', session_signout_path, method: :delete %></li>
          </ul>

          <span style="float:right;"><%= link_to image_tag(current_user.avatar.thumb.url, height: "56px;"), user_path(current_user) %></span>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Teams <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% if current_user.teams.blank? %>
                  <li>No Teams Assigned</li>
                <% else %>
                  <% current_user.teams.each do |team| %>
                    <li><%= link_to team.name, [team.league, team] %></li>
                  <% end %>
                <% end %>
              </ul>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Leagues <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% League.all.each do |league| %>
                  <li><%= link_to league.skill, league %></li>
                <% end %>
              </ul>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', root_path %></li>
          </ul>

          <% if current_user.admin? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Admin", admin_root_path %></li>
            </ul>
          <% end %>

          <p class="navbar-text navbar-left">Hello <%= current_user.name %>!</p>

      <% else %>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Sign up!', new_user_path %></li>
        </ul>

        <%= form_tag({controller: 'session', action: "signin"}, class: "navbar-form navbar-right") do %>
          <%= text_field_tag(:email, nil, placeholder: 'Email') %>
          <%= password_field_tag(:password, nil, placeholder: 'Password') %>
          <%= submit_tag("Sign In") %>
        <% end %>

      <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IceSportsForum</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:600' rel='stylesheet' type='text/css'>
</head>

<body>
  <div id="wrapper">

    <div id="header"><%= render :partial => 'layouts/navbar' %></div>

    <div id="content">
      <div class="container-fluid">
        <%= yield %>
      </div>
    </div>

    <div id=footer>
      <div class="navfooter">
        <p class="element">
          website designed and managed by Kyle Swartz | Ice Sports Forum |
          (813) 481-1293 | email kyle.swartz.3@gmail.com |
          <%= link_to 'Home', root_path %>
        </p>
      </div>
    </div>

  </div>
</body>

</html>